"""sessions table

Revision ID: c5ea7d44234e
Revises: b5361819265b
Create Date: 2021-03-11 15:04:11.241705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ea7d44234e'
down_revision = 'b5361819265b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('imageString', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'imageString')
    # ### end Alembic commands ###
