"""sessions table

Revision ID: faed6ba536c5
Revises: c5ea7d44234e
Create Date: 2021-05-26 20:57:16.562426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faed6ba536c5'
down_revision = 'c5ea7d44234e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('nextSessionDate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_session_nextSessionDate'), 'session', ['nextSessionDate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_nextSessionDate'), table_name='session')
    op.drop_column('session', 'nextSessionDate')
    # ### end Alembic commands ###
